WKTElement: fix __str__ under python 3
In py3, WKTElement.desc() returns string and WKBElement.desc() returns
bytes, so the __str__ implementation in the subclass needs to handle both.

>  str(WKTElement('POINT(1 2)')
AttributeError("'str' object has no attribute 'decode'")